### ISSUE TITLE
Extra pixels at bottom of channel column on mobile

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#100] opened 2020-06-07 22:04 UTC
See below the last channel here 

![Screenshot_20200608-000217](https://user-images.githubusercontent.com/613432/83981130-85aadd00-a91b-11ea-81f3-b09041c7144e.png)
Chrome on Android

**Comment by jjandoc** [comment] 2020-06-07 22:24
So that's caused by us removing infinite scroll on mobile. To accomplish the infinite scroll effect, I was cloning all the channels so the scrolling looked seamless. This doubled the height of the contents which 99% of the time meant you'd never see the end of the content on any normal screen. Now we're not doing that, and the iframe is hard-coded to be 1000px tall. That space you're seeing is the difference between the full height of the content and 1000px. Again, if they can style the iframe to be proportional to the screen - 90vh for 90% of the viewport height - that would be an easy fix for this.

**Comment by mstem** [comment] 2020-06-07 23:19
OK, in that case we have a request in for this

**Closed** 2020-06-12 17:14 UTC
