### ISSUE TITLE
Liveguide.us tag updates

### ISSUE THREAD

**Issue by mstem** [exafox/paquete#122] opened 2020-06-18 13:14 UTC
In the site's meta tags -
- Swap out the Boston.com favicon for the BostonGlobe.com favicon
- Add the social preview images
[sm_previews_grid2 (5).zip](https://github.com/exafox/paquete/files/4799009/sm_previews_grid2.5.zip)

**Comment by jjandoc** [comment] 2020-06-21 22:32
I can update the favicon, but the social preview images are identical to what we have right now with the blue cells. Is that correct? Should they be with black cells reflecting current designs?

**Comment by jjandoc** [comment] 2020-06-21 22:35
Favicon updated by https://github.com/exafox/paquete/commit/1b4210221875198d525c83c9053b0fda44fd735e.

**Comment by jjandoc** [comment] 2020-06-28 17:25
Closing as the remaining work is a duplicate of #32

**Closed by jjandoc** 2020-06-28 17:25 UTC
